# Generated by Django 5.1.7 on 2025-04-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_notification_purchaseorder_purchaseorderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="product",
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity_ordered", models.IntegerField()),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("expected_delivery_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.inventory"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.supplier"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DemandForecasting",
        ),
        migrations.DeleteModel(
            name="PurchaseOrder",
        ),
        migrations.DeleteModel(
            name="PurchaseOrderItem",
        ),
    ]
