# Generated by Django 5.1.7 on 2025-04-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customer_sales_status_sales_customer_delete_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sales",
            name="customer",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
